---
title: "Regression Models Course Project Report"
author: "YE"
date: "15 mai 2016"
output: pdf_document
---

The goal of this project is to investigate througth the relationship between a set of variables and the Miles per Galon in the MTCARS dataset.

---


```{r}
summary(cars)
```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
